#!/bin/bash
# git aliases
GIT_EXCLUDES="old|gtk-perl|external|school|inactive"
GIT_PATH="/home/brian/src"
alias gitrefchk="/bin/bash ~/bin/git-tool.sh --path=${GIT_PATH} \
    --exclude \"${GIT_EXCLUDES}\" refchk"
# these next two are the same
alias gitstat="/bin/bash ~/bin/git-tool.sh --path=${GIT_PATH} \
    --exclude \"${GIT_EXCLUDES}\" repostat"
alias gitrepostat="/bin/bash ~/bin/git-tool.sh --path=${GIT_PATH} \
    --exclude \"${GIT_EXCLUDES}\" repostat"
alias gitinchk="/bin/bash ~/bin/git-tool.sh --path=${GIT_PATH} \
    --exclude \"${GIT_EXCLUDES}\" inchk"
alias gitoutchk="/bin/bash ~/bin/git-tool.sh --path=${GIT_PATH} \
    --exclude \"${GIT_EXCLUDES}\" outchk"
alias gitpullall="/bin/bash ~/bin/git-tool.sh --path=${GIT_PATH} \
    --exclude \"${GIT_EXCLUDES}\" pullall"
# vi: set filetype=sh shiftwidth=4 tabstop=4
# fin!
